In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 2x2 대칭행렬로 고유값, 특이값분해를 해보겠습니다.

In [187]:
x=np.array([[2,1],[1,2]])    ;x #출력

array([[2, 1],
       [1, 2]])

In [188]:
# EVD : AV=λV
s,v=np.linalg.eig(x);np.linalg.eig(x) 

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [189]:
# A = VΛV^-1
np.dot(np.dot(v,np.diag(s)),np.linalg.inv(v))

array([[2., 1.],
       [1., 2.]])

In [190]:
np.dot(v,v.T) #직교행렬검증

array([[1., 0.],
       [0., 1.]])

In [191]:
# SVD : A=U∑V^T
u,s,v = np.linalg.svd(x) ; np.linalg.svd(x) 

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3., 1.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### 4x2 직사각행렬

In [142]:
A=np.array([[1,2],[3,2],[0,0],[0,0]]);A

array([[1, 2],
       [3, 2],
       [0, 0],
       [0, 0]])

In [143]:
# SVD : A=U∑V^T
u,s,v = np.linalg.svd(A)     ;np.linalg.svd(A)#출력 

(array([[-0.50192682, -0.86491009,  0.        ,  0.        ],
        [-0.86491009,  0.50192682,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([4.13064859, 0.96837093]),
 array([[-0.74967818, -0.66180256],
        [ 0.66180256, -0.74967818]]))

In [144]:
# AA^T
AAT=np.dot(A,A.T);np.dot(A,A.T)

array([[ 5,  7,  0,  0],
       [ 7, 13,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [145]:
# A^TA
ATA=np.dot(A.T,A);np.dot(A.T,A)

array([[10,  8],
       [ 8,  8]])

In [175]:
# AA^Tu = λu 
s,u=np.linalg.eig(AAT);np.linalg.eig(AAT)  

(array([ 0.93774225, 17.06225775,  0.        ,  0.        ]),
 array([[-0.86491009, -0.50192682,  0.        ,  0.        ],
        [ 0.50192682, -0.86491009,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [159]:
# A^TAv = λv 
s,v=np.linalg.eig(ATA);np.linalg.eig(ATA)

(array([17.06225775,  0.93774225]),
 array([[ 0.74967818, -0.66180256],
        [ 0.66180256,  0.74967818]]))

In [183]:
#s=np.concatenate([np.diag(s),np.array([[0,0],[0,0]])],axis=1)

In [184]:
# ∑ 매트릭스 모양으로 변형 
# s[np.nonzero(s)] nonzero index만 추출
s=np.concatenate([np.diag(s[np.nonzero(s)]),np.array([[0,0],[0,0]])],axis=0)
np.sqrt(s) #출력

array([[0.96837093, 0.        ],
       [0.        , 4.13064859],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [185]:
us=np.dot(u,np.sqrt(s))  ;np.dot(u,np.sqrt(s))#출력

array([[-0.83755379, -2.0732833 ],
       [ 0.48605134, -3.57263965],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [186]:
# SVD : A=U∑V^T
np.dot(us,v)

array([[-2., -1.],
       [-2., -3.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [148]:
#s=np.concatenate([np.diag(s),np.array([[0],[0]])],axis=1)

In [85]:
np.linalg.svd(A)

(array([[-0.8816746 , -0.47185793],
        [-0.47185793,  0.8816746 ]]),
 array([7.60555128, 0.39444872]),
 array([[-0.47185793, -0.8816746 ],
        [ 0.8816746 , -0.47185793]]))

In [86]:
A=np.array([[3,6],[2,3],[0,0],[0,0]])

In [87]:
u,s,v=np.linalg.svd(A)
np.linalg.svd(A)

(array([[-0.8816746 , -0.47185793,  0.        ,  0.        ],
        [-0.47185793,  0.8816746 ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([7.60555128, 0.39444872]),
 array([[-0.47185793, -0.8816746 ],
        [ 0.8816746 , -0.47185793]]))