In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A=np.array([[2,-1],[3,1]])
x=[2,-1]
y=[3,1]

In [3]:
a=([[2,1],[1,2]])

In [4]:
np.linalg.eig(a)

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [5]:
v=([[1,1],[1,-1]])
np.linalg.inv(v)

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [6]:
np.linalg.svd(a)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3., 1.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [7]:
s1,v1=np.linalg.eig(A)
np.linalg.eig(A)

(array([1.5+1.6583124j, 1.5-1.6583124j]),
 array([[0.14433757+0.47871355j, 0.14433757-0.47871355j],
        [0.8660254 +0.j        , 0.8660254 -0.j        ]]))

In [8]:
s2,v2=np.linalg.eig(A.T)
np.linalg.eig(A.T)

(array([1.5+1.6583124j, 1.5-1.6583124j]),
 array([[ 0.8660254 +0.j        ,  0.8660254 -0.j        ],
        [-0.14433757+0.47871355j, -0.14433757-0.47871355j]]))

In [9]:
np.round(np.dot(v1,v2),10)

array([[ 0.33333333+0.5527708j, -0.125     +0.4145781j],
       [ 0.625     +0.4145781j,  0.625     -0.4145781j]])

In [10]:
v1.T

array([[0.14433757+0.47871355j, 0.8660254 +0.j        ],
       [0.14433757-0.47871355j, 0.8660254 -0.j        ]])

In [11]:
np.dot(v1.T,v)

array([[ 1.01036297+0.47871355j, -0.72168784+0.47871355j],
       [ 1.01036297-0.47871355j, -0.72168784-0.47871355j]])

### 2x3

In [12]:
# m x n test
A=np.array([[2,1,3],[1,2,3]])

In [13]:
u,s,v = np.linalg.svd(A)
np.linalg.svd(A)

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([5.19615242, 1.        ]),
 array([[ 4.08248290e-01,  4.08248290e-01,  8.16496581e-01],
        [-7.07106781e-01,  7.07106781e-01,  6.86286675e-17],
        [-5.77350269e-01, -5.77350269e-01,  5.77350269e-01]]))

In [21]:
np.dot(v[1].T,v[2])

-1.824218252474059e-16

In [14]:
#(A.A^T)u
b=np.dot(A,A.T)
np.dot(A,A.T)

array([[14, 13],
       [13, 14]])

In [15]:
np.linalg.svd(b)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([27.,  1.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [16]:
c=np.dot(A.T,A)
np.dot(A.T,A)

array([[ 5,  4,  9],
       [ 4,  5,  9],
       [ 9,  9, 18]])

In [67]:
s,u =np.linalg.eig(c)
np.linalg.eig(c)

(array([ 2.70000000e+01,  1.00000000e+00, -2.43466418e-16]),
 array([[-4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
        [-4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
        [-8.16496581e-01, -5.96409950e-17,  5.77350269e-01]]))

In [55]:
u,s,v = np.linalg.svd(c)
np.linalg.svd(c)

(array([[-4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
        [-4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
        [-8.16496581e-01, -4.34250533e-16,  5.77350269e-01]]),
 array([2.70000000e+01, 1.00000000e+00, 1.44214109e-15]),
 array([[-4.08248290e-01, -4.08248290e-01, -8.16496581e-01],
        [ 7.07106781e-01, -7.07106781e-01, -1.13851925e-15],
        [-5.77350269e-01, -5.77350269e-01,  5.77350269e-01]]))

In [68]:
(u[0][0])**2+(u[1][0])**2+(u[2][0])**2

1.0

In [19]:
# A*V
np.dot(A,v.T)

array([[ 3.67423461, -0.70710678,  0.        ],
       [ 3.67423461,  0.70710678,  0.        ]])

In [20]:
# U*S
s=np.concatenate([np.diag(s),np.array([[0],[0]])],axis=1)
np.dot(u,s)

array([[ 3.67423461, -0.70710678,  0.        ],
       [ 3.67423461,  0.70710678,  0.        ]])

In [21]:
np.dot(np.dot(u,s),v)

array([[2., 1., 3.],
       [1., 2., 3.]])

### 3 x 2

In [22]:
A=np.array([[2,1],[1,2],[3,1],[4,1]])

In [23]:
u,s,v=np.linalg.svd(A)
np.linalg.svd(A)

(array([[-0.37988723, -0.11396958, -0.54945274, -0.7353899 ],
        [-0.28516406, -0.92264063,  0.04669264,  0.25541247],
        [-0.53809069,  0.11759758,  0.77205704, -0.31710746],
        [-0.69629416,  0.34916474, -0.31598957,  0.54167243]]),
 array([5.86633024, 1.60815719]),
 array([[-0.92807377, -0.37239639],
        [ 0.37239639, -0.92807377]]))

In [24]:
np.round(np.dot(u,u.T))

array([[ 1., -0., -0., -0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])

In [25]:
np.dot(A,v.T)

array([[-2.22854394, -0.18328099],
       [-1.67286655, -1.48375116],
       [-3.15661771,  0.1891154 ],
       [-4.08469148,  0.56151179]])

In [26]:
np.concatenate([s,np.array([0,0])])

array([5.86633024, 1.60815719, 0.        , 0.        ])

In [27]:
s=np.diag(np.concatenate([s,np.array([0,0])]))

In [28]:
us=np.dot(u,s)
us[:,:2]

array([[-2.22854394, -0.18328099],
       [-1.67286655, -1.48375116],
       [-3.15661771,  0.1891154 ],
       [-4.08469148,  0.56151179]])

In [29]:
np.dot(us[:,:2],v)

array([[2., 1.],
       [1., 2.],
       [3., 1.],
       [4., 1.]])

In [30]:
np.linalg.eig(np.dot(A,A.T))

(array([3.44138305e+01, 2.58616954e+00, 1.79440026e-17, 1.03231657e-15]),
 array([[-0.37988723,  0.11396958, -0.22450419,  0.91691299],
        [-0.28516406,  0.92264063,  0.16883805, -0.23786365],
        [-0.53809069, -0.11759758, -0.73285796, -0.16878043],
        [-0.69629416, -0.34916474,  0.61968605, -0.27240526]]))

In [31]:
np.linalg.eig(np.dot(A.T,A))

(array([34.41383046,  2.58616954]),
 array([[ 0.92807377, -0.37239639],
        [ 0.37239639,  0.92807377]]))

In [32]:
np.linalg.svd(A)

(array([[-0.37988723, -0.11396958, -0.54945274, -0.7353899 ],
        [-0.28516406, -0.92264063,  0.04669264,  0.25541247],
        [-0.53809069,  0.11759758,  0.77205704, -0.31710746],
        [-0.69629416,  0.34916474, -0.31598957,  0.54167243]]),
 array([5.86633024, 1.60815719]),
 array([[-0.92807377, -0.37239639],
        [ 0.37239639, -0.92807377]]))

In [33]:
d=np.array([[-0.37988723, -0.11396958, -0.54945274, -0.7353899 ],
        [-0.28516406, -0.92264063,  0.04669264,  0.25541247],
        [-0.53809069,  0.11759758,  0.77205704, -0.31710746],
        [-0.69629416,  0.34916474, -0.31598957,  0.54167243]])

In [34]:
# 직교행렬 확인
np.round(np.dot(d,d.T))

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [ 0., -0., -0.,  1.]])

### #####################

In [35]:
#v=([[2,1],[3,1]])

In [36]:
lam=np.diag(sorted(np.linalg.eig(a)[0], reverse=True))

In [37]:
np.dot(v,lam)

array([[-2.78422132, -0.37239639],
       [ 1.11718917, -0.92807377]])

In [38]:
np.dot(np.dot(v,lam),np.linalg.inv(v))

array([[ 2.72264186, -0.69122265],
       [-0.69122265,  1.27735814]])

In [39]:
np.linalg.inv(v)

array([[-0.92807377,  0.37239639],
       [-0.37239639, -0.92807377]])

In [40]:
b=([1,3,-1,2],[1,1,3,-2])

In [41]:
np.dot(a,b)

array([[ 3,  7,  1,  2],
       [ 3,  5,  5, -2]])

In [42]:
a=([[2,-1],[1,-2]])

In [43]:
np.linalg.eig(a)

(array([ 1.73205081, -1.73205081]),
 array([[0.96592583, 0.25881905],
        [0.25881905, 0.96592583]]))

### 대칭행렬

In [44]:
a=np.array([[2,1,3],[1,2,1],[3,1,2]])

In [45]:
np.linalg.svd(a)

(array([[-6.57192300e-01,  2.60956474e-01, -7.07106781e-01],
        [-3.69048184e-01, -9.29410263e-01, -1.59154867e-16],
        [-6.57192300e-01,  2.60956474e-01,  7.07106781e-01]]),
 array([5.56155281, 1.43844719, 1.        ]),
 array([[-6.57192300e-01, -3.69048184e-01, -6.57192300e-01],
        [ 2.60956474e-01, -9.29410263e-01,  2.60956474e-01],
        [ 7.07106781e-01, -3.96348516e-16, -7.07106781e-01]]))

In [46]:
t=np.array([[-6.57192300e-01,  2.60956474e-01, -7.07106781e-01],
        [-3.69048184e-01, -9.29410263e-01, -1.59154867e-16],
        [-6.57192300e-01,  2.60956474e-01,  7.07106781e-01]])

In [47]:
np.round(np.dot(t,t.T))

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [48]:
np.dot(a,a.T)

array([[14,  7, 13],
       [ 7,  6,  7],
       [13,  7, 14]])

In [49]:
np.dot(a.T,a)

array([[14,  7, 13],
       [ 7,  6,  7],
       [13,  7, 14]])

### ####

In [50]:
A=([[1,2],[3,4]])

In [51]:
b=([[1,1],[1,-1]])

In [52]:
np.dot(A,b)

array([[ 3, -1],
       [ 7, -1]])

In [53]:
np.linalg.svd(A)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))